### ISSUE TITLE
locale has to be generated on system and postgres has to know it

### ISSUE THREAD

**Issue by dirks** [geerlingguy/ansible-role-postgresql#100]
Using a fresh vagrant vm (ubuntu/bionic64) the only enabled locale is `en_US.UTF-8 UTF-8`. Therefore when setting

```
postgresql_databases:                                                                                                                                                                                                                                                         
  - name: testdb                                                                                                                                                                                                                                                       
    lc_collate: de_DE.UTF-8                                                                                                                                                                                                                                                   
    lc_ctype: de_DE.UTF-8                                                                                                                                                                                                                                                     
    owner: user
``` 

db creation fails
```
TASK [geerlingguy.postgresql : Ensure PostgreSQL databases are present.] **************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: psycopg2.ProgrammingError: invalid locale name: "de_DE.UTF-8"
failed: [pg1.dev] (item={u'owner': u'user u'lc_collate': u'de_DE.UTF-8', u'name': u'testdb', u'lc_ctype': u'de_DE.UTF-8'}) => {"ansible_loop_var": "item", "changed": false, "item": {"lc_collate": "de_DE.UTF-8", "lc_ctype": "de_DE.UTF-8", "name": "testdb", "owne
r": "user"}, "msg": "Database query failed: invalid locale name: \"de_DE.UTF-8\"\n"}                                                  
```
As a quick fix I included the following into my playbook

```
  pre_tasks:                                                                                                                                                                                                                                                                  
    - name: ensure locales exist                                                                                                                                                                                                                                              
      locale_gen:                                                                                                                                                                                                                                                             
        name: '{{ item }}'                                                                                                                                                                                                                                                    
        state: present                                                                                                                                                                                                                                                        
      loop:                                                                                                                                                                                                                                                                   
        - en_US.UTF-8                                                                                                                                                                                                                                                         
        - de_DE.UTF-8
```

but I needed to restart postgresql as well to pick up the new locale.
