### ISSUE TITLE
Creating postgresql_users fails because the user's database doesn't exist.

### ISSUE THREAD

**Issue by lorf** [geerlingguy/ansible-role-postgresql#103]
When freshly installing the PostgreSQL instance using geerlingguy.postgresql role version 2.0.1 and the postgresql_databases and postgresql_users is populated like this:
```
postgresql_databases:
  - name: SOMEDB
postgresql_users:
  - name: SOMEUSER
    db: SOMEDB
```
the playbook fails with the error: `OperationalError: FATAL:  database "SOMEDB" does not exist`.

I would expect it to create the database first then create the user belonging to the database. But found that the creation order was recently changed in PR #31. Downgrading the role to version 1.4.7 works as expected. What is the correct way to specify the database the user should belong to?
