### ISSUE TITLE
no_log setting can not be overridden

### ISSUE THREAD

**Issue by occoder** [geerlingguy/ansible-role-postgresql#110]
I'd like to override no_log setting in role's task "Ensure Postgresql users are present" for troubleshooting.
However, ansible-playbook playbook.yml -e 'no_log=false' was not able to do so.
The failed log shows "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result".

**Comment by renannprado** [comment]
@occoder meanwhile you can add `-vvvv` to you ansible playbook execution command line and you'll have more details

**Comment by renannprado** [comment]
@occoder I've created a fork where I removed that option.

If you want to try it out, you can have the following file

```yaml
- name: geerlingguy.postgresql
  version: patch
  src: https://github.com/renannprado/ansible-role-postgresql.git
```

Then you run:

```sh
ansible-galaxy install -r requirements.yaml
```

And your local version of the role will be using the forked version instead.
You can have your and do whatever changes you want before sending a patch to this repository as well.
