### ISSUE TITLE
Configure global settings fail.

### ISSUE THREAD

**Issue by michaeloa** [geerlingguy/ansible-role-postgresql#111]
Setting up the role on a fresh Ubuntu 18.04 VM install, I get the following error message:

```
: Configure global settings.] *******************************************************************
failed: [10.141.65.51] (item={u'option': u'listen_addresses', u'value': u'*'}) => {"ansible_loop_var": "item", "changed": false, "item": {"option": "listen_addresses", "value": "*"}, "msg": "Destination /etc/postgresql/10/main/postgresql.conf does not exist !", "rc": 257}
```

The role is configured as follows:
```
    - role: g.postgresql
      vars:
        postgresql_locales:
          - 'en_US.UTF-8'
        postgresql_global_config_options:
          - option: listen_addresses
            value: '*'
        postgresql_hba_entries:
          - { type: local, database: all, user: postgres, auth_method: peer }
          - { type: local, database: all, user: all, auth_method: peer }
          - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
          - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
        postgresql_users:
          - name: "{{ db_user }}"
            password: "{{ db_pass }}"
        postgresql_databases:
          - name: "{{ db_name }}"
            owner: "{{ db_user }}"
```

I can resolve the issue by manually logging into the server, running an apt-get install purge on postgresql-10, and then re-running the role. Seems like the first install that the role performs is faulty, somehow (despite it being a completely newly created VM).
