### ISSUE TITLE
Integer values for PostgreSQL configuration

### ISSUE THREAD

**Issue by vnea** [geerlingguy/ansible-role-postgresql#117]
Hello,

In the **configure.yml** task, we can configure the PostgreSQL with this task :
```yml
- name: Configure global settings.
  lineinfile:
    dest: "{{ postgresql_config_path }}/postgresql.conf"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_global_config_options }}"
  notify: restart postgresql
```

If I define this item : 
```
- option: max_connections
  value: "5"
```

The rendered option will be :
```
max_connections = '5'
```

Is it OK for PostgreSQL configuration that the integer value is single quoted ?
If not, is there a workaround to have the integer value without the quotes ?
