### ISSUE TITLE
Wrong regex to configure postgresql.conf

### ISSUE THREAD

**Issue by fcecagno** [geerlingguy/ansible-role-postgresql#120]
I configure this in my yaml:

```
postgresql_global_config_options:
  - option: pg_stat_statements.track
    value: top
  - option: pg_stat_statements.track_utility
    value: 'true'
```

Every time I run the playbook, it replaces `pg_stat_statements.track_utility.*` by `pg_stat_statements.track = 'top'`, and add a new `pg_stat_statements.track_utility = 'true'`, so I end up with:
```
pg_stat_statements.track = 'top'
pg_stat_statements.track = 'top'
pg_stat_statements.track = 'top'
pg_stat_statements.track = 'top'
pg_stat_statements.track = 'top'
pg_stat_statements.track = 'top'
pg_stat_statements.track = 'top'
pg_stat_statements.track_utility = 'true'
```

I suggest you change the regex on https://github.com/geerlingguy/ansible-role-postgresql/blob/master/tasks/configure.yml#L5 by something like:
```
regexp: "^#?{{ item.option }}[^\w\.].+$"
```
(making sure that the following character after the option name isn't a letter or a dot)
