### ISSUE TITLE
Postgres 9.6

### ISSUE THREAD

**Issue by NiftyMist** [geerlingguy/ansible-role-postgresql#123]
How could one adapt this role to install Postgres 9.6 on Centos7/RHEL7?

**Comment by kdhlab** [comment]
Something like this should work:
```
---
- hosts: all
  tasks:
    - yum:
        name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
        state: present
      become: yes
    - import_role:
        name: geerlingguy.postgresql
      vars:
        postgresql_enablerepo: "pgdg96"
        postgresql_version: 9.6
        postgresql_packages:
          - postgresql96
          - postgresql96-server
          - postgresql96-contrib
          - postgresql96-libs
        postgresql_data_dir: /var/lib/pgsql/9.6/data
        postgresql_bin_path: /usr/pgsql-9.6/bin
        postgresql_config_path: /var/lib/pgsql/9.6/data
        postgresql_daemon: postgresql-9.6
      become: yes
```
