### ISSUE TITLE
Chicken Egg problem with users and databases

### ISSUE THREAD

**Issue by breml** [geerlingguy/ansible-role-postgresql#125]
In the beginning of this role, the databases have been created first and the users after. This allowed to use the `db` setting on the `postgresql_users`. Since https://github.com/geerlingguy/ansible-role-postgresql/commit/929fe7ed3c1920d7278ab9b57fc6a59d31e58166#diff-2444ad0870f91f17ca6c2a5e96b26823 this has been changed, such that the users are created first and the databases second. This allows to set the `owner` on `postgresql_databases` but now the `db` on `postgresql_users` is no longer working.

I guess the only way to fix this is to first create the users and the databases and apply the `db` setting for the `postgresql_users` in a second step, when all databases have been created.

**Comment by hyclak** [comment]
I ran into this issue as well. I created a later task to use the postgresql_privs module to accomplish that:

```
postgresql_privs:
  db: postgres
  privs: ALL
  type: database
  obj: thedb
  role: theuser
become: yes
become_user: postgres
```

It would be much more convenient to be able to just `db: thedb` in the role!
