### ISSUE TITLE
Changing `listen_addresses`

### ISSUE THREAD

**Issue by 2hamed** [geerlingguy/ansible-role-postgresql#136]
Is there anyway to change the default `listen_addresses` config? I could not find anything about it anywhere.

**Comment by croensch** [comment]
I wrote my own task:
```yaml
  tasks:
    - name: "postgres | fix listen adress"
      become: true
      lineinfile:
        dest: "/etc/postgresql/{{ postgresql_version }}/main/conf.d/listen.conf"
        regexp: '^#?listen_addresses='
        line: "listen_addresses='{{ postgres_listen_addresses|default('localhost') }}'"
        state: present
        create: yes
      notify: 'restart postgresql'
      tags: postgres_fix
```

**Comment by anhdat** [comment]
It's in `postgresql_global_config_options`

>Global configuration options that will be set in `postgresql.conf`

```yaml
postgresql_global_config_options:
  - option: listen_addresses
    value: "*"
```
