### ISSUE TITLE
Can't change postgres_version

### ISSUE THREAD

**Issue by GoodBoy962** [geerlingguy/ansible-role-postgresql#145]
Adding var postgresql_version: "12" doesn't change actual version which was installed in VM with Ubuntu 18.

**Comment by JakeCooper** [comment]
Also noticed this on Debian 10

**Comment by europ** [comment]
@geerlingguy is it possible to specify a custom psql version that will be installed via this ansible role?

### Problem

This role does not support installation of custom PSQL version to the destination platform.

### Notes

```
---------------------------------------
postgresql_version: [OS-specific]
postgresql_data_dir: [OS-specific]
postgresql_bin_path: [OS-specific]
postgresql_config_path: [OS-specific]
postgresql_daemon: [OS-specific]
postgresql_packages: [OS-specific]
---------------------------------------

OS-specific variables that are set by include files in this role's vars
directory. These shouldn't be overridden unless you're using a version
of PostgreSQL that wasn't installed using system packages.
```

The default PSQL version is defined in `./vars/<OS>-<version>.yml`, e.g.:
https://github.com/geerlingguy/ansible-role-postgresql/blob/master/vars/RedHat-7.yml#L2

### Example

Platform:
* CentOS-7
    * includes systemd
    * includes sshd
    * container ([setup](https://github.com/europ/docker-centos-sshd-systemd#quick-run))

Playbook:
```yml
---
- hosts: container # src: https://hub.docker.com/r/europ/docker-centos-sshd-systemd
  gather_facts: true
  tasks:
    - block: # workaround, see https://stackoverflow.com/a/56558842
        - name: PSQL installation and configuration
          include_role:
            name: geerlingguy.postgresql
          vars:
            postgresql_users:
              - name: abc
                password: abc
            postgresql_databases:
              - name: xyz
            postgresql_version: "10.4" # override psql-9.2 with custom version (psql-10.4)
      become: true
```

Result:
```sh
psql -V
# psql (PostgreSQL) 9.2.24
```

**Comment by yodatak** [comment]
Same for me on debian 10 ....

**Comment by MystaMax** [comment]
Hello. I'm not 100% sure of this but if you specify a different version of PostgreSQL using `postgresql_version`, you need to configure the rest of the `postgres_` variables. Otherwise, it will use the defaults from `./vars/<OS>-<version>.yml` for the variables you did not define and will conflict with the version you wish to install.

For example, in my CentOS 6 test environment, I wanted to install PostgreSQL v9.6. That version of PostgreSQL is not in the standard CentOS repositories. These playbooks by Jeff only use the default repositories. Verify that the version of PostgreSQL you wish to install is in the repositories enabled on your server. In my case, I had to install the official PostgreSQL v9.6 yum repositories before configuring the role:

```yaml
    - name: Install PostgreSQL 9.6 Repository
      yum_repository:
        name: postgresql96
        baseurl: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-$releasever-$basearch
        enabled: True
        file: postgresql96
        description: PostgreSQL 9.6 for RHEL/CentOS $releasever - $basearch
        gpgcheck: False
```

I added the following variables to `./vars/main.yml` NOTE: This file did not exist and had to be created. Also, note the variables below only work on RHEL-based distributions. These will be different for Debian-based distributions.

```yaml
postgres_users_no_log: false # not needed; enabled for troubleshooting
postgresql_version: "9.6"
postgresql_data_dir: /var/lib/pgsql/9.6/data
postgresql_bin_path: /usr/pgsql-9.6/bin
postgresql_config_path: /var/lib/pgsql/9.6/data
postgresql_daemon: postgresql-9.6
postgresql_packages:
  - postgresql96
  - postgresql96-libs
  - postgresql96-server
```

Once you have all these variables defined, it will hopefully work for you as well.
