### ISSUE TITLE
Feature Request: Support for Database Extensions

### ISSUE THREAD

**Issue by rehashedsalt** [geerlingguy/ansible-role-postgresql#157]
As it stands, the current role does not have a built-in method of managing database extensions. While a post-task in a playbook for [`postgresql_ext`](https://docs.ansible.com/ansible/latest/collections/community/general/postgresql_ext_module.html) is a manageable workaround, it suffers from some drawbacks:

* It fragments configuration between a role and its post-tasks (solvable with var files, I guess)

* It requires manual declaration of redundant arguments, such as `login_host`, `login_user`, etc.

It would be much more elegant to have a list of extensions (or some variation of this) be included in each database declared in `postgresql_databases`. For example:

```yaml
postgresql_databases:
  - name: foo
    owner: foo
    extensions:
      - name: citext
      - name: pg_trgm
      - name: uuid-ossp
        state: absent
```

Would a PR adding a loop task in `database.yml` be welcome?
