### ISSUE TITLE
FR: ability to install from pgdg repo (needs apt key) and control the version that is actually installed

### ISSUE THREAD

**Issue by jeanmonet** [geerlingguy/ansible-role-postgresql#159]
The variable `postgresql_version` does not seem to be actually used to control which version will be installed. Instead, the default version available on apt is being installed:

https://github.com/geerlingguy/ansible-role-postgresql/blob/180fac804842610e6bdac05730ed4506dc596629/vars/Ubuntu-20.yml#L2-L11

It would be nice to be able to install from the pgdg repo and choose the version, for example to be able to install verison 13 on Ubuntu 20. See for ex https://github.com/galaxyproject/ansible-postgresql/blob/master/tasks/debian.yml

**EDIT**: maybe this was actually a design decision since we can pass the `postgresql_packages` variable and explicitly specify `postgresql-13` for example? Adding the apt key `https://www.postgresql.org/media/keys/ACCC4CF8.asc` before running the role is left to the user.

**EDIT 2:** It's also required to pass in `postgresql_data_dir` `postgresql_bin_path` `postgresql_config_path` variables which over-ride those in snippet above.

**EDIT 3**: `postgresql_data_dir` variable does not change it in PostgreSQL's `postgresql.conf` (**not sure this is intended behavior?**). So I passed it via the role's `postgresql_global_config_options` var. This allows for `postgresql.conf` to reference the desired data dir path.

**Comment by aviatrix** [comment]
There's a PR about the version thing #156 
while this PR is being reviewed, you can use my galaxy `aviatrix.postgresql` which is 1:1 as the PR version.

**Comment by jeanmonet** [comment]
Thanks. I think the difficulty with this role is to have identical api for all supported platforms (not just Ubuntu). IMO after some thought I think it would require more profound changes to do it properly. I think the current design lets you achieve this if you prepare 1/ apt key and repo and 2/ the variables to be fed.

What I've done is wrap this role (a playbook will also do) in my own custom role where I install the apt key and repo, set the variables and pass them to the role (of course this only applies to Ubuntu):

```yaml

# Add apt key for pgdg repo
- name: Install pgdg package signing key from Postgresql.org URL (Debian/pgdg)
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    id: ACCC4CF8
  register: __postgresql_apt_key_result
  until: __postgresql_apt_key_result is succeeded
  retries: 5
  delay: 5
  ignore_errors: True

# Fail-proof, probably non necessary
- name: Install pgdg package signing key from MIT keyserver (Debian/pgdg)
  apt_key:
    keyserver: pgp.mit.edu
    id: ACCC4CF8
  register: __postgresql_apt_key_result
  until: __postgresql_apt_key_result is succeeded
  retries: 5
  delay: 5
  when: __postgresql_apt_key_result is not succeeded

- fail:   # not sure it's necessary, the play will probably fail anyway if apt key cannot be obtained in above task
    msg: Could not install apt key
  when: __postgresql_apt_key_result is not succeeded

- name: Install pgdg repository (Debian/pgdg)
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    update_cache: yes


# Install PostgreSQL with role "geerlingguy.postgresql"
- name: Install and configure PostgreSQL
  include_role:
    name: geerlingguy.postgresql
  vars:
    # vars below are customly prepared and passed to this role. This allows custom-version installation on Ubuntu/Debian
    postgresql_version: "{{ var_postgres_version }}"
    postgresql_data_dir: "{{ var_postgres_data_dir }}"
    postgresql_bin_path: "{{ var_postgres_bin_path }}"
    postgresql_config_path: "{{ var_postgres_config_path }}"
    postgresql_global_config_options: "{{ var_postgres_global_config_options }}"
    postgresql_users: "{{ var_postgres_users }}"
    postgresql_databases: "{{ var_postgres_dbs }}"
    postgres_users_no_log: False    # TEMP

```
