### ISSUE TITLE
Issue creating a user

### ISSUE THREAD

**Issue by guleyupo** [geerlingguy/ansible-role-postgresql#170]
I am stuck and Google is no help! When I run my playbook that had normally worked I get the following error output on a new system. This may be due to this other RedHat 7.8 system being different or more secure or whatnot. I tried switching from 2.x to 3.1 release and made no difference. The error does not help me much. Here is the error and the variables I define:

```
TASK [geerlingguy.postgresql : Ensure PostgreSQL users are present.] **************************************************************************************
task path: /xxxx/roles/geerlingguy.postgresql/tasks/users.yml:2
Saturday 27 March 2021  17:28:30 +0000 (0:00:00.728)       0:00:30.870 ********
failed: [myhost.example.com] (item={u'password': u'plaintextpassword', u'name': u'postgres'}) => changed=false
  ansible_loop_var: item
  item:
    name: postgres
    password: u'plaintextpassword
  msg: |-
    unable to connect to database: FATAL:  parameter "password_encryption" requires a Boolean value
```

My vars are defined as:

```
postgresql_users:
  - name: postgres
    password: u'plaintextpassword'
postgres_users_no_log: false

# /var/lib/pgsql/data/postgresql.conf
postgresql_global_config_options:
  - {option: max_connections, value: 200}
  - {option: max_prepared_transactions, value: 64}
  - {option: shared_buffers, value: 128MB}
  - {option: work_mem, value: 128MB}
  - {option: listen_addresses, value: '*'}

# /var/lib/pgsql/data/pg_hba.conf
postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: peer }
  - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
  - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
  - { type: host, database: all, user: all, address: '172.20.0.0/16', auth_method: md5 }
  - { type: host, database: all, user: all, address: '10.0.2.15/32', auth_method: md5 }
  - { type: host, database: all, user: all, address: '192.168.0.0/16', auth_method: md5 }
```

I tried adding 'encrypted' options of true/false/on/off to my postgresql_users but seems to make no difference. On the target system the server is seemeingly installed correctly and is upand listening. also the /etc/passwd file has the `postgres:x:26:26:PostgreSQL Server:/var/lib/pgsql:/bin/bash` entry.

Thanks for any advice you could offer.
