### ISSUE TITLE
Issue with password alogirthm

### ISSUE THREAD

**Issue by cryptolukas** [geerlingguy/ansible-role-postgresql#172]
Hi,

i made the experience with a small implementation issue.
If you use the role like snippet below. You stuck in password authentication failures. 
The default is still md5. So if you install postgres and create the database within the same run you create md5 passwords NOT scram-sha-256 password.

My recoomendation. If you change something with `postgresql_global_config_options` you need to restart. I know you can't use handlers and it's dirty but a task could fix it :D

```
  - hosts: all
    become: true
    roles:
      - role: geerlingguy.postgresql
    vars:
      postgresql_python_library: python3-psycopg2
      postgresql_global_config_options:
        - option: password_encryption
          value: 'scram-sha-256'
        - option: listen_addresses
          value: 'localhost, 127.0.0.1, xxx.xxx.xxx.xxx'
      postgresql_databases:
        - name: gitea
          lc_collate: en_US.UTF-8
          lc_ctype: en_US.UTF-8
          encoding: UTF8
          template: template0
          owner: # defaults to postgresql_user
          state: present
      postgresql_users:
        - name: gitea_user
          password: supersecure
      postgresql_user: postgres
      postgresql_group: postgres
      postgresql_unix_socket_directories:
        - /var/run/postgresql
      postgresql_service_state: started
      postgresql_service_enabled: true
      postgresql_locales:
        - 'en_US.UTF-8'
      postgresql_hba_entries:
        - { type: local, database: all, user: postgres, auth_method: peer }
        - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: scram-sha-256 }
        - { type: host, database: all, user: all, address: '::1/128', auth_method: scram-sha-256 }
        - { type: local, database: gitea, user: gitea_user, auth_method: scram-sha-256 }
        - { type: host, database: gitea, user: gitea_user, address: '127.0.0.1/32', auth_method: scram-sha-256 }
```
