### ISSUE TITLE
Postgres doesn't restart automatically

### ISSUE THREAD

**Issue by marasiali** [geerlingguy/ansible-role-postgresql#173]
Hi, I set `postgresql_hba_entries` incorrectly, so I got an error in task `TASK [geerlingguy.postgresql : Ensure PostgreSQL users are present.]` that said `unable to connect to database: FATAL:  no pg_hba.conf entry for host`.
I corrected it by changing `postgresql_hba_entries`. but the error remains. It seems pg_hba.conf not updated.
The reason is that postgres service doesn't restart automatically. It fixed by manually restarting postgres service.

If you see [configure task](https://github.com/geerlingguy/ansible-role-postgresql/blob/master/tasks/configure.yml), `restart postgresql` handler called after configuring pg_hba.conf.

```
- name: Configure host based authentication (if entries are configured).
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_config_path }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0600
  notify: restart postgresql
  when: postgresql_hba_entries | length > 0
```

But according to [Ansible Docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html#controlling-when-handlers-run):

> By default, handlers run after all the tasks in a particular play have been completed. 

and when `TASK [geerlingguy.postgresql : Ensure PostgreSQL users are present.]` failed, playbook running terminated, and `restart postgresql` never called.
