### ISSUE TITLE
Order of operations error, task/variables.yml

### ISSUE THREAD

**Issue by r-pufky** [geerlingguy/ansible-role-postgresql#174]
This was an awkward issue to track down.

Currently, when overriding the system defaults (vars/{os}-{version}.yml) you **must** override all variables within, regardless if they are composed variables or not.

Example case: I want to install postgres 12.
``host_vars/host/main.yml``
```yaml
postgresql_version: 12
postgresql_packages:
  - postgresql-12
  - postgresql-contrib-12
  - libpq-dev
```

## Behavior
Assuming I do all the repo prep before running this role, the assumption is that this should work, as the role defaults will take care of the rest. however, the calculated variables **always use** the role vars regardless leading to version mis-match errors when running:

This task will always fail, checking ``/var/lib/postgresql/11/main`` instead of ``/var/lib/postgresql/12/main``
```yaml
- name: Ensure PostgreSQL database is initialized.
  command: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
```

This happens because composed variables **always use** the role vars, ``__postgresql_*`` instead of preferring user-defined variables.

So the current workaround is to:
``host_vars/host/main.yml``
```yaml
postgresql_version: 12
postgresql_data_dir: '/var/lib/postgresql/{{ postgresql_version }}/main'
postgresql_bin_path: '/usr/lib/postgresql/{{ postgresql_version }}/bin'
postgresql_config_path: '/etc/postgresql/{{ postgresql_version }}/main'
postgresql_daemon: 'postgresql@{{ postgresql_version }}-main'
postgresql_packages:
  - postgresql-12
  - postgresql-contrib-12
  - libpq-dev
postgresql_python_library: python3-psycopg2
```

Which essentially requires you to dig deep into the role to figure out, after debugging wonky error messages based on composed variables. This isn't intuitive or user friendly.

## Expectation
Set user-defined variables and the role will use/calculate **role-specific variables** that are used internally on the role automatically if not defined.

## Proposal
When processing variables, find the user-defined variables and overlay them on the role/vars, producing a composed variable used for the rest of the role. This fixes the OOO errors and enables minimal role-specific knowledge to apply settings to the role.

1. set composed variables, using user defined variable if defined.
1. set composed variables, using defaults from vars/ os-specific variables, only set if the composed variable is not already set.
1. proceed as normal.

This would include updating all os templates ``vars/*`` to using a new composed variable for ``_postgres_version`` et. al. as well as updating the logic in ``tasks/variables.yml`` to the aforementioned method.
