### ISSUE TITLE
Setting global config timezone results in duplicate timezone lines.

### ISSUE THREAD

**Issue by r-pufky** [geerlingguy/ansible-role-postgresql#176]
# Before running

`host_vars`
```yaml
postgresql_global_config_options:
  ...
  - option: timezone
    value: 'America/Los_Angeles'
```

`/etc/postgresql/11/main/postgresql.conf`
```
...
timezone = 'Etc/UTC'
...
```

# After running task
`/etc/postgresql/11/main/postgresql.conf`
```
...
timezone = 'Etc/UTC'
timezone = 'America/Los_Angeles'
...
```

Maybe `postgresql.conf` should be managed from a template with defaults instead generic regex's? Regex is notorious difficult to get right.
