### ISSUE TITLE
Setting ssl on/off results in duplication postgresql.conf lines.

### ISSUE THREAD

**Issue by r-pufky** [geerlingguy/ansible-role-postgresql#177]
Similiar to issue #176 

# Before running

`host_vars`
```yaml
postgresql_global_config_options:
  ...
  - option: ssl
    value: 'off'
```

`/etc/postgresql/11/main/postgresql.conf`
```
...
ssl = on
...
```

# After running task
`/etc/postgresql/11/main/postgresql.conf`
```
...
ssl = on
... rest of ssl block ...
ssl = 'off'
...
```

Note: Using boolean interpreted values here (e.g. `host_vars` `value: off` results in `ssl = False` in the conf)

Again, maybe `postgresql.conf` should be managed from a template with defaults instead generic regex's? Regex is notorious difficult to get right.
