### ISSUE TITLE
Arch Linux support

### ISSUE THREAD

**Issue by C0rn3j** [geerlingguy/ansible-role-postgresql#189]
I was able to get the role working on Arch Linux with the following variables:
```
    __postgresql_version: "13"
    __postgresql_data_dir: "/var/lib/postgres/data"
    __postgresql_bin_path: "/usr/sbin"
    __postgresql_config_path: "/var/lib/postgres/data"
    __postgresql_daemon: "postgresql"
    __postgresql_packages:
      - postgresql
```

However it does not install the postgresql package using pacman, so that has to be done manually still.
