### ISSUE TITLE
Fix Debian build failures when adding Databases and Users

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-postgresql#2]
I get the message:

```
unable to connect to database: fe_sendauth: no password supplied
```

On Ubuntu 16, 14, and Debian 8; see https://travis-ci.org/geerlingguy/ansible-role-postgresql/builds/163833924

Things succeed on CentOS 6 and 7.

**Comment by geerlingguy** [comment]
Gah, in Vagrant environment, where I am not SSHing as root (but rather as `vagrant`), I've run into: https://github.com/ansible/ansible/issues/16048

**Comment by geerlingguy** [comment]
Fix for the comment above was to add the following to all the postgres tasks:

```yaml
  become: yes
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
```

But I'm still hitting the 'no password supplied error. Looks like I'm going to have to template the other config files.
