### ISSUE TITLE
Add listen_addresses to postgresql_global_config_options example and defaults

### ISSUE THREAD

**Issue by bubthegreat** [geerlingguy/ansible-role-postgresql#201]
Trying to figure out how this all worked and had to dig into the exact commands to see how to expose the database: 

There might be a graceful way to do both, but for now just adding the example and the defaults would be helpful for those of us jumping into the role.

```
        postgresql_global_config_options:
          - option: unix_socket_directories
            value: '{{ postgresql_unix_socket_directories | join(",") }}'
          - option: listen_addresses
            value: '*'
```

Thanks for all the work on this.
