### ISSUE TITLE
Ensure PostgreSQL users are present [Failed]

### ISSUE THREAD

**Issue by libert-xyz** [geerlingguy/ansible-role-postgresql#226]
OS: Ubuntu 20.04
Ansible version: 2.13.3

Getting the following error

_msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: invalid mode: 'A+user:postgres:rx:allow'\nTry 'chmod --help' for more information.\n}). For information on working around this, see https://docs.ansible.com/ansible-core/2.13/user_guide/become.html#risks-of-becoming-an-unprivileged-user"}_

Installing `acl` fixed the issue

```
- name: Ensure PostgreSQL packages are installed.
  apt:
    name: acl
    state: present
```
