### ISSUE TITLE
I am not able to create users and databases

### ISSUE THREAD

**Issue by reeshabhranjan** [geerlingguy/ansible-role-postgresql#227]
```An exception occurred during task execution. To see the full traceback, use -vvv. The error was: psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: fe_sendauth: no password supplied```

```
- hosts: all
  roles:
    - role: geerlingguy.postgresql
      become: yes
      vars:
        postgresql_databases:
          - name: db1
            login_host: 127.0.0.1
            owner: user1
        postgresql_users:
          - name: user1
            password: password1
...
```
