### ISSUE TITLE
Role fails when used with AWX (Ansible Tower) without FQCN

### ISSUE THREAD

**Issue by MrRoyce** [geerlingguy/ansible-role-postgresql#249]
Hi there, this worked fine for me when I tested on a local VM.  However it failed on a remote AWX server because it could not find 2 modules.   I had to add the following to a `collections\requirements.yml` file to get this to work:

```
---
collections:
- name: community.postgresql
  source: https://galaxy.ansible.com

- name: community.general
  source: https://galaxy.ansible.com
```
Hope this helps someone else.
