### ISSUE TITLE
If the locale name is specific to ICU, use ICU_LOCALE

### ISSUE THREAD

**Issue by mikysal78** [geerlingguy/ansible-role-postgresql#274]
Hi, i use fresh install debian 12.9 and i have this error:

```
TASK [geerlingguy.postgresql : Ensure PostgreSQL databases are present.] ****************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NOTA: If the locale name is specific to ICU, use ICU_LOCALE.
failed: [controller.nnxx.ninux.org] (item={'name': 'openwisp2'}) => changed=false 
  ansible_loop_var: item
  item:
    name: openwisp2
  msg: |-
    Database query failed: ERRORE:  invalid LC_COLLATE locale name: "en_US.UTF-8"
    NOTA: If the locale name is specific to ICU, use ICU_LOCALE.
```

i try this playbook:
```
- hosts: postgres
  become: "{{ become | default('yes') }}"
  roles:
    - geerlingguy.postgresql
  vars:
    # PostgrSQL
    postgresql_locales:
      - 'it_IT.UTF-8'
    postgresql_unix_socket_directories:
      - /var/run/postgresql
    postgresql_databases:
      - name: openwisp2
    #    #state: absent # defaults to 'present'
    postgresql_users:
      - name: openwisp2
        password: nNxxBas2024
        lc_collate: 'it_IT.UTF-8'
        lc_ctype: 'it_IT.UTF-8'
        encoding: 'UTF-8'
    #    #encrypted: no
        role_attr_flags: CREATEDB,CREATEROLE,SUPERUSER
    #    priv: ALL
        db: openwisp2
        #state: absent # defaults to 'present'

  pre_tasks:
      - name : install postgis extension for postgres
        become: yes
        register: aptinstall
        apt:
           name: 
            - postgresql-17-postgis-3
            - postgresql-17-postgis-3-scripts
           state: latest
           update_cache: yes
```
My Locales is:
```
root@controller:~ # locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
root@controller:~ # 
```
