### ISSUE TITLE
How do you install from PostgresSQL YUM repository

### ISSUE THREAD

**Issue by worldofchris** [geerlingguy/ansible-role-postgresql#38]
Hi,

I'm trying to use this role to install PostgresSQL 9.6 on Centos 7.

It's fine doing 9.2 which is in the base repos but I cannot work out how to configure it to use the PostgresSQL YUM repository in order to get 9.6.

What is the value that needs to go in the `postgresql_enablerepo` variable?

I can only find the repository rpms e.g. `https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm`

When I set:

` postgresql_enablerepo: "https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm"`

It results in the error:

`"Error setting/accessing repos: Error getting repository data for https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm, repository not found"`

Can you see what I am doing wrong?

Thanks

**Comment by worldofchris** [comment]
I _think_ I have answered this myself.

I ran:

`yum install https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm`

Then looking in `/etc/yum.repos.d/pgdg-96-centos.repo` I found the name `pgdg96`.  Setting `postgresql_enablerepo` to this resulted in `postgresql96-libs` being pulled from `pgdg96` but everything else (`postgresql`, `postgresql-contrib` etc) still coming from `updates`.

So I followed the instructions at https://wiki.postgresql.org/wiki/YUM_Installation to exclude `postgresql*` from `base` and `updates`.

I then re-ran the playbook with the role and got 9.6 installed.

Is this the right way to do it or am I working around my own ineptitude?

Thanks

**Comment by matthiase** [comment]
Hi @worldofchris, I ran into the same issue trying to install PostgreSQL 9.6 on CentOS 7 and your approach got me started down the correct road. However, I still ran into some problems because Postgres is not being installed from system packages. After several unsuccessful attempts, I noticed the section in the README that addresses using non-system packages and came up with the following:

```
- hosts: all
  gather_facts: true

  pre_tasks:
    - name: make selinux permissive
      selinux:
        policy: targeted
        state: permissive
      become: yes

    - name: install PostgreSQL 9.6 repository
      yum:
        name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
        state: present
      become: yes

  tasks:
    - name: install system packages
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - "@Development tools"
      become: yes

  roles:
    - role: geerlingguy.postgresql
      postgresql_enablerepo: "pgdg96"
      postgresql_version: 9.6
      postgresql_data_dir: /var/lib/pgsql/9.6/data
      postgresql_bin_path: /usr/pgsql-9.6/bin
      postgresql_config_path: /var/lib/pgsql/9.6/data
      postgresql_daemon: postgresql-9.6.service
      postgresql_packages:
        - postgresql96
        - postgresql96-server
        - postgresql96-libs
        - postgresql96-contrib
        - postgresql96-devel
      become: yes
```

It turns out that you have to be very specific about the version-specific variables but it all seems to work now and I did not have to make any changes to CentOS-Base.repo. Hopefully this helps you out.

**Comment by madeinoz67** [comment]
thanks @worldofchris @matthiase both helped me considerably!

**Comment by po5i** [comment]
Awesome help. This should be documented in a wiki or something

**Comment by maksimluzik** [comment]
If someone wants to get PostgreSQL 10 running with ansible role, I managed to get it working with the following ansible playbook:

```
- hosts: all

  pre_tasks:
  - name: install PostgreSQL 10 repository
    yum:
      name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7.5-x86_64/pgdg-redhat10-10-2.noarch.rpm
      state: present
    become: yes

  tasks:


  roles:
    - role: geerlingguy.postgresql
      postgresql_enablerepo: "pgdg10"
      postgresql_version: 10
      postgresql_data_dir: /var/lib/pgsql/10/data
      postgresql_bin_path: /usr/pgsql-10/bin
      postgresql_config_path: /var/lib/pgsql/10/data
      postgresql_daemon: postgresql-10.service
      postgresql_packages:
        - postgresql10
        - postgresql10-server
        - postgresql10-libs
        - postgresql10-contrib
        - postgresql10-devel
      become: yes
```
