### ISSUE TITLE
How to change the PGDATA dir

### ISSUE THREAD

**Issue by zerr0s** [geerlingguy/ansible-role-postgresql#40]
Hello,

I'm trying to change the PGDATA default dir. I've set "postgresql_data_dir" to another dir (/var/postgresql/data for example). The initdb is working fine, but the service is not starting
because the systemd daemon is looking for /var/lib/pgsql/9.6/data

Is it possible to change the data dir using this role ?

Thanks.

**Comment by anroots** [comment]
Kindof hackish way of doing it using the role's own methods: define a variable.

```yaml
postgresql_global_config_options:
  - option: data_directory
    value: "/external_disk/postgres/10"
```

**Comment by sir-sukhov** [comment]
It's worth to mention that both steps are mandatory, thus:

```YAML
postgresql_data_dir: /external_disk/postgres/10
postgresql_global_config_options:
  - option: data_directory
    value: "/external_disk/postgres/10"
```

**Comment by dgptamayo** [comment]
I tried setting the variables mentioned above but the default systemd manifest file for postgresql (/usr/lib/systemd/system/postgresql.service) still use the default PGDATA value:

```
# Location of database directory
Environment=PGDATA=/var/lib/pgsql/data
```

**Comment by sir-sukhov** [comment]
observed one more thing to do with this role for PGDATA change on Ubuntu 18.04
it's due to handler.
correct [steps] to change PGDATA during first installation seems to be:
[install postgres] -> [change config] -> [restart postgres] -> [create database]

but Ansible plays handler after all tasks, so it works like that:
[install postgres] -> [change config] -> [create database] -> [restart postgres]

thus, database I tried to create appeared in the output of "\d" psql command only after applying this role twice.

workaround seems to be "- meta: flush_handlers" inside tasks/main.yml
```
- include_tasks: configure.yml
- include_tasks: initialize.yml
- meta: flush_handlers
```

and I also changed handler to make it sleep in systemd:

```
---
- name: make postgres restart
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_restarted_state }}"
    sleep: 5
  listen: "restart postgresql"

- name: wait for 5 seconds
  wait_for: timeout=5
  delegate_to: localhost
  listen: "restart postgresql"
```
