### ISSUE TITLE
psycopg2 module is required (module present)

### ISSUE THREAD

**Issue by svanschalkwyk** [geerlingguy/ansible-role-postgresql#48]
1. pip list shows psycopg2 (2.7.5)
2. yum shows this Package python-psycopg2-2.7.5-1.rhel7.x86_64 already installed and latest version
2a: python --version: Python 2.7.5
3. Ansible yml has this:
```
  roles:
    - role: ansible-role-postgresql
      become: yes
      postgresql_enablerepo: "pgdg96"
      postgresql_restarted_state: "restarted"
      postgresql_python_library: python-psycopg2
      postgresql_bin_path: /usr/pgsql-9.6/bin
      postgresql_daemon: postgresql-9.6.service 
```

4. Error thrown is this: 

```TASK [ansible-role-postgresql : Ensure PostgreSQL databases are present.] ****************************************************************************
failed: [clpaxd-iwh01.na.ad.rrd.com] (item={u'owner': u'manifold', u'login_user': u'manifold', u'name': u'manifoldcf', u'login_password': u'manifold'}) => {"changed": false, "item": {"login_password": "manifold", "login_user": "manifold", "name": "manifoldcf", "owner": "manifold"}, "msg": "the python psycopg2 module is required"}
```
Environment:
1. Centos 7
2. Python 2.7.5
3. ansible 2.7.0.dev0 (stable-2.6 28d0a173db) last updated 2018/06/25 12:12:39 (GMT -500)

Any idea how to fix this?
