### ISSUE TITLE
Create users before databases

### ISSUE THREAD

**Issue by char16t** [geerlingguy/ansible-role-postgresql#49]
This section at `tasks/main.yml`:
```
# Configure PostgreSQL.                                                                                                                               
- import_tasks: databases.yml                                                                                                                         
- import_tasks: users.yml
```
should be
```
# Configure PostgreSQL.                                                                                                                               
- import_tasks: users.yml
- import_tasks: databases.yml                                                                                                                         
```

When I trying create user and database that he own like this:
```
postgresql_users:                                                                                                                                     
  - name: project                                                                                                                                     
    password: projectpassword                                                                                                                         
postgresql_databases:                                                                                                                                 
  - name: project                                                                                                                                     
    owner: project
```

I got error: 
>  role "project" does not exist
