### ISSUE TITLE
Changing listen port breaks user configuration

### ISSUE THREAD

**Issue by sduthil** [geerlingguy/ansible-role-postgresql#51]
I'd like to configure my PostgreSQL server to listen on a different port, e.g. 5433. Here goes:

Given I have the following role vars:
```
        postgresql_global_config_options:
          - option: port
            value: 5433
        postgresql_users:
          - name: user
            port: 5433
```
When I run my playbook
Then I get an error about the user creation:
```
unable to connect to database: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5433"?
```

What happens AFAIU:
1. the `postgresql.conf` is changed with `port = 5433`
2. PostgreSQL is not restarted
3. To create the new user, Ansible connects to PostgreSQL with `port: 5433` but cannot find the correct Unix socket, because PostgreSQL is still listening on 5432

**Alternate scenario**
If I don't specify the `port` option in `postgresql_users`:

Given I have the following role vars:
```
        postgresql_global_config_options:
          - option: port
            value: 5433
        postgresql_users:
          - name: user
```
When I run my playbook once
When I run my playbook twice
Then I get an error about the user creation:
```
unable to connect to database: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

~~Given I work with Debian, I worked around the problem by configuring an additional `postgresql_locales`, forcing an early restart of PostgreSQL by triggering [this task](https://github.com/geerlingguy/ansible-role-postgresql/blob/master/tasks/setup-Debian.yml#L18)~~
Edit: Wrong, the restart is done too early, before `postgresql.conf` is changed.

**Comment by sduthil** [comment]
Here is what I ended up doing:

```
- hosts: database
  pre_tasks:
    - name: Change PostgreSQL port
      become: yes
      include_role: 
        name: geerlingguy.postgresql
      vars:
        postgresql_global_config_options:
          - option: port
            value: 5433
        postgresql_users: []
  roles:
    - role: geerlingguy.postgresql
      become: yes
      vars:
        postgresql_users:
          - name: postgres
            password: superpass
            port: 5433
```

The handlers for `pre_tasks` are run before running the roles tasks, so PostgreSQL is restarted by the `pre_tasks` changes before trying to configure the database users in the `roles`
