### ISSUE TITLE
Dynamically creating pg_hba.conf from postgresql_databases and postgresql_users?

### ISSUE THREAD

**Issue by beargiles** [geerlingguy/ansible-role-postgresql#57]
I've  set up my vars so that I can allow access to my database via the internet. (Filtering is handled elsewhere.)

```yml
- postgresql_databases:
   - name: testdb
- postgresql_users:
   - name: testuser
- postgresql_hba_entries:
   - {type: host, database: testdb, user: testuser, address: all, auth_method: md5}
- postgresql_global_config_options:
   - option: listen_addresses
     value: '*'
```

Since we already have postgresql_databases and postgresql_users values I would prefer to use a Cartesian product to create the pg_hba entries but don't see how to do it. list1|lookup('cartisian' list2) wouldn't have all of the required fields. Creating my own pg_hba.conf.j2 template would work but would I have to fork this project?

I'll be switching to LDAP authentication soon but would still prefer to iterate over the postgresql_databases list if possible.

Ideas?
