### ISSUE TITLE
Debian-10 Buster support 

### ISSUE THREAD

**Issue by simevo** [geerlingguy/ansible-role-postgresql#68]
Please support the upcoming stable.

**Comment by ieugen** [comment]
Hi, Debian buster is very close to being released. I have started migrating some of my servers since already. It would be great to have this supported as soon as possible.

Thanks,

**Comment by ieugen** [comment]
There is a workaround until support is officialy added: 

- build your own `Debian-10.yml` file
- use `set_facts` to put the version for Debian (if needed - in my case yes because the version is reported as *buster/sid* - I have a 2-3 packages installed from sid )

My Debian-10.yml 
```
---
__postgresql_version: "11"
__postgresql_data_dir: "/var/lib/postgresql/{{ __postgresql_version }}/main"
__postgresql_bin_path: "/usr/lib/postgresql/{{ __postgresql_version }}/bin"
__postgresql_config_path: "/etc/postgresql/{{ __postgresql_version }}/main"
__postgresql_daemon: "postgresql@{{ postgresql_version }}-main"
__postgresql_packages:
  - postgresql
  - postgresql-contrib
  - libpq-dev
```
How i set facts:
```
---
- name: Setup PostgreSQL database and db tooling
  hosts: dbservers
  pre_tasks:
    - name: Pre tasks actions
      set_fact:
        # Workaround for Debian Buster - https://github.com/geerlingguy/ansible-role-postgresql/issues/68
        "ansible_distribution_major_version": "10"
        "ansible_distribution_release": "buster"
        "ansible_distribution_version": "10"
```
