### ISSUE TITLE
password error when running playbook

### ISSUE THREAD

**Issue by cue232s** [geerlingguy/ansible-role-postgresql#8]
I'm following your example, to no avail and am getting the following error.  I'm using ansible 2.1.2.0, and my target is ubuntu/trusty64. Any clue what the issue could be? 

```bash
TASK [setup] *******************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE"}
``` 

postgres.yml
```yaml 
---
- hosts: localhost
  become: true
  vars_files:
    - vars/postgresql.yml
  roles:
    - geerlingguy.postgresql
```

postgresql.yml

```yaml
---
postgresql_group: postgres

postgresql_locales:
  - 'en_US.UTF-8'


ostgresql_databases:
 - name: testdb # required; the rest are optional
    # lc_collate: # defaults to 'en_US.UTF-8'
    # lc_ctype: # defaults to 'en_US.UTF-8'
    # encoding: # defaults to 'UTF-8'
    # template: # defaults to 'template0'
    # login_host: # defaults to 'localhost'
    # login_user: # defaults to 'postgresql_user'
    # login_unix_socket: # defaults to 1st of postgresql_unix_socket_directories
    # port: # defaults to not set
    # state: # defaults to 'present'
postgresql_users:
  - name: testdb #required; the rest are optional
    password: testdb
    # priv: # defaults to not set
    # role_attr_flags: # defaults to not set
    # db: # defaults to not set
    # login_host: # defaults to 'localhost'
    # login_user: # defaults to '{{ postgresql_user }}'
    # login_unix_socket: # defaults to 1st of postgresql_unix_socket_directories
    # port: # defaults to not set
    # state: # defaults to 'present'
```
