### ISSUE TITLE
Ubuntu 18.04.02 - PostgreSQL Not Enabled on Start

### ISSUE THREAD

**Issue by mcglonelevi** [geerlingguy/ansible-role-postgresql#80]
I am attempting to run this Ansible role against a Ubuntu 18.04.02 LTS server.  Here is my playbook.yml file:

```
- name: Provision Python
  hosts: all
  gather_facts: no
  tasks:
    - name: Boostrap python
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)

- name: Install Ruby
  hosts: all
  roles:
    - role: ansible-role-ruby

- name: Install NodeJS
  hosts: all
  roles:
    - ansible-role-nodejs

- name: Install PostgreSQL
  hosts: all
  roles:
    - role: ansible-role-postgresql
      become: yes

- name: Modify .bashrc
  hosts: all
  tasks:
    - name: Execute items in profile.d
      lineinfile:
        path: /root/.bashrc
        line: |
          if [ -d /etc/profile.d ]; then
            for i in /etc/profile.d/*.sh; do
              if [ -r $i ]; then
                . $i
              fi
            done
            unset i
          fi

```

When the server is restarted, PostgreSQL does not launch on start.  From what I can tell, `postgresql_service_enabled is true` by default, so I do not understand why it does not start.

Have I done something wrong here or is there a bug?
