### ISSUE TITLE
Configuring pg_hba.conf is skipped though the var is set

### ISSUE THREAD

**Issue by floriandammeyer** [geerlingguy/ansible-role-postgresql#87]
I am using the Ansible local provisioner to set up a Vagrant test machine. The installed Postgresql database server should trust any incoming connection, so my playbook.yml looks something like this:

```
---
- name: Set up the Vagrant development server
  hosts: all
  become: yes
  vars:
    postgresql_hba_entries:
      - { type: local, database: all, user: all, auth_method: trust }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: trust }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: trust }
  roles:
    - role: geerlingguy.postgresql
```

Installation works, but the postgresql role is skipping the step to configure the pg_hba.conf file, meaning I have to manually make my changes in pg_hba.conf to connect to the database server.

Is there a mistake in my playbook.yml or might this be a bug because my configuration is "too similar" to the defaults?
